# Generated by Django 4.1.6 on 2023-02-11 22:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=225)),
                ('street', models.CharField(max_length=225)),
                ('apartment', models.CharField(max_length=4)),
                ('phone', models.CharField(default='+380000000000', max_length=12, verbose_name='Contact us:')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(default='+380000000000', max_length=12, unique=True, verbose_name='Contact:')),
                ('birth_date', models.DateField(null=True)),
                ('registration_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('individual', 'Individual'), ('group', 'Group'), ('independent', 'Independent')], default='independent', max_length=20)),
                ('per_num', models.CharField(default=0, max_length=7, verbose_name='Personal number')),
                ('status', models.CharField(choices=[('30', '30'), ('8', '8'), ('12', '12')], default='unlimited', max_length=2)),
                ('is_activated', models.BooleanField(default=False, verbose_name='Active')),
                ('due_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Expires')),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
            },
        ),
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datagym.address')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datagym.client')),
            ],
            options={
                'verbose_name': 'Gym',
                'verbose_name_plural': 'Gyms',
            },
        ),
        migrations.AddField(
            model_name='client',
            name='subscription_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datagym.subscription'),
        ),
    ]
