# Generated by Django 4.1.6 on 2023-02-12 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datagym', '0002_alter_address_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('30', '30'), ('8', '8'), ('12', '12')], default='30', max_length=2),
        ),
    ]
