# Generated by Django 4.1.6 on 2023-02-13 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datagym', '0003_alter_subscription_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gym',
            name='client',
        ),
        migrations.AddField(
            model_name='gym',
            name='clients',
            field=models.ManyToManyField(to='datagym.client'),
        ),
    ]
